export { HARNESS_CATALOG, harnessById } from './catalog.js'
export type { ExecutionFamily, HarnessDefinition, HarnessId } from './catalog.js'
export { apply, Config, inject, name } from './plugin.js'
export type { Config as HarnessPluginConfig } from './plugin.js'
export { REACT_PROMPT } from './harnesses/react.js'
